AllCops:
  Exclude:
    - 'spec/**/*'
    - db/schema.rb
    - 'test/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Layout/Tab:
  Enabled: false
