DB_USERNAME: 'postgres'
DB_PASSWORD: 'password'

development:
  DB_NAME_DEV: sample_app_development

test:
  DB_NAME_TEST: sample_app_test

production:
  DB_USERNAME: ''
  DB_PASSWORD: ''
  DB_NAME_PROD: sample_app_production
